// ../../sw/kt/fgcepics/fgcudpSup/src/common/inc/class_selector.h - This file is automatically generated by `parser/Output/EPICS/asynDriver/FGC_handler_fact.pm`  DO NOT EDIT

#include "class_base_params.h"

#include "classes/62/class_62_params.h"
#include "classes/63/class_63_params.h"



ClassHandler * createFGChandler(int fgc_tag, int fgc_id, int class_id)
{
    switch(class_id)
    {
        case 62:
            return new Class62(fgc_id, fgc_tag);
        case 63:
            return new Class63(fgc_id, fgc_tag);
        default:
            return NULL;
    }
}



// End of file: ../../sw/kt/fgcepics/fgcudpSup/src/common/inc/class_selector.h
