// ../../sw/globals/inc/classes/63/63_stat.h - This file is automatically generated by `parser/Output/C/FGC_stat.pm`  DO NOT EDIT

#include <stdint.h>
#ifndef FGC63_STAT
#define FGC63_STAT

struct fgc63_stat
{
    uint16_t st_faults       ;  // Faults
    uint16_t st_warnings     ;  // Warnings
    uint16_t st_latched      ;  // Latched status
    uint16_t st_unlatched    ;  // Unlatched status
    uint8_t  state_pll       ;  // Phase-locked loop state
    uint8_t  state_op        ;  // Operational state
    uint8_t  state_vs        ;  // Voltage source state
    uint8_t  state_pc        ;  // Power converter state
    uint8_t  st_adc_a        ;  // ADC A status
    uint8_t  st_adc_b        ;  // ADC B status
    uint8_t  st_adc_c        ;  // ADC C status
    uint8_t  st_adc_d        ;  // ADC D status
    uint8_t  st_dcct_a       ;  // DCCT A status
    uint8_t  st_dcct_b       ;  // DCCT B status
    int16_t  i_err_ma        ;  // Error between current reference and measurement (mA)
    int16_t  i_diff_ma       ;  // Difference in current measurements (mA)
    uint8_t  event_group     ;  // Reference event group
    int8_t   i_earth_pcnt    ;  // Earth fault current (percent of trip level)
    float    i_ref           ;  // Current reference (A)
    float    i_meas          ;  // Current measurement (A)
    float    v_ref           ;  // Voltage reference (V)
    float    v_meas          ;  // Voltage measurement (V)
};
#endif
// End of file: ../../sw/globals/inc/classes/63/63_stat.h
