// ../../sw/lib/fgceth/fgcepics/fgcudpSup/src/classes/63/class_63_params.h - This file is automatically generated by `parser/Output/EPICS/asynDriver/FGC_handler.pm`  DO NOT EDIT

#ifndef CLASS_63_PARAMS_H
#define CLASS_63_PARAMS_H

#include <asynPortDriver.h>
#include "pub_data.h"
#include "class_base_params.h"

#define ASYN_PARAMS_63   22
#define ASYN_CLASS_ID_63 63



class Class63 : public ClassHandler
{
protected:
    const int class_id;
    int param_id[ASYN_PARAMS_63];

public:
    Class63(int id, int addr) : ClassHandler(id, addr), class_id(ASYN_CLASS_ID_63) {};
    virtual void create_class_params(asynPortDriver * drv);
    virtual void update_class_params(asynPortDriver * drv, Pub_data & pub_data);
    virtual void invalidate_class_params(asynPortDriver * drv);
};



#endif
// End of file: ../../sw/lib/fgceth/fgcepics/fgcudpSup/src/classes/63/class_63_params.h
