// ../../sw/kt/fgcepics/fgcudpSup/src/classes/class_62_params.cpp - This file is automatically generated by `parser/Output/EPICS/asynDriver/FGC_handler.pm`  DO NOT EDIT

#include <alarm.h>
#include <string>

#include <asynPortDriver.h>

#include "pub_data.h"
#include "param_utils.h"
#include "class_base_params.h"
#include "classes/62/class_62_params.h"
#include "classes/62/sub_defsyms.h"
#include "classes/62/sub_defconst.h"

#define NAME_BUFFER_LEN 256

void Class62::create_class_params(asynPortDriver * drv)
{
    ClassHandler::create_class_params(drv);
    int dev_tag = get_tag();
    char name_buffer[NAME_BUFFER_LEN];

    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "ST_FAULTS");
    drv->createParam(name_buffer, asynParamOctet  , &param_id[0]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "ST_WARNINGS");
    drv->createParam(name_buffer, asynParamOctet  , &param_id[1]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "ST_LATCHED");
    drv->createParam(name_buffer, asynParamOctet  , &param_id[2]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "ST_UNLATCHED");
    drv->createParam(name_buffer, asynParamOctet  , &param_id[3]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "STATE_PLL");
    drv->createParam(name_buffer, asynParamOctet  , &param_id[4]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "STATE_OP");
    drv->createParam(name_buffer, asynParamOctet  , &param_id[5]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "STATE_VS");
    drv->createParam(name_buffer, asynParamOctet  , &param_id[6]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "STATE_PC");
    drv->createParam(name_buffer, asynParamOctet  , &param_id[7]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "ST_ADC_A");
    drv->createParam(name_buffer, asynParamOctet  , &param_id[8]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "ST_ADC_B");
    drv->createParam(name_buffer, asynParamOctet  , &param_id[9]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "ST_ADC_C");
    drv->createParam(name_buffer, asynParamOctet  , &param_id[10]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "ST_ADC_D");
    drv->createParam(name_buffer, asynParamOctet  , &param_id[11]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "ST_DCCT_A");
    drv->createParam(name_buffer, asynParamOctet  , &param_id[12]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "I_EARTH_PCNT");
    drv->createParam(name_buffer, asynParamInt32  , &param_id[13]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "I_ERR_MA");
    drv->createParam(name_buffer, asynParamInt32  , &param_id[14]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "I_REF");
    drv->createParam(name_buffer, asynParamFloat64, &param_id[15]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "I_MEAS");
    drv->createParam(name_buffer, asynParamFloat64, &param_id[16]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "V_MEAS");
    drv->createParam(name_buffer, asynParamFloat64, &param_id[17]);
    snprintf(name_buffer, NAME_BUFFER_LEN, "%d_%s", dev_tag, "V_CAPA");
    drv->createParam(name_buffer, asynParamFloat64, &param_id[18]);

    drv->setStringParam( param_id[0] , "");
    drv->setStringParam( param_id[1] , "");
    drv->setStringParam( param_id[2] , "");
    drv->setStringParam( param_id[3] , "");
    drv->setStringParam( param_id[4] , "");
    drv->setStringParam( param_id[5] , "");
    drv->setStringParam( param_id[6] , "");
    drv->setStringParam( param_id[7] , "");
    drv->setStringParam( param_id[8] , "");
    drv->setStringParam( param_id[9] , "");
    drv->setStringParam( param_id[10], "");
    drv->setStringParam( param_id[11], "");
    drv->setStringParam( param_id[12], "");
    drv->setIntegerParam(param_id[13], 0);
    drv->setIntegerParam(param_id[14], 0);
    drv->setDoubleParam( param_id[15], 0);
    drv->setDoubleParam( param_id[16], 0);
    drv->setDoubleParam( param_id[17], 0);
    drv->setDoubleParam( param_id[18], 0);
};



void Class62::update_class_params(asynPortDriver * drv, Pub_data & pub_data)
{
    ClassHandler::update_class_params(drv, pub_data);
    int dev_id   = get_id();

    //Check if class 62 data is valid
    if(
        !(pub_data.status[dev_id].data_status & FGC_DATA_VALID)  ||
        !(pub_data.status[dev_id].data_status & FGC_CLASS_VALID) ||
        (pub_data.status[dev_id].class_id != class_id)
    )
    {
        for(int i = 0; i < ASYN_PARAMS_62; i++)
        {
            drv->setParamStatus(param_id[i], asynSuccess); // Force callback
            drv->setParamStatus(param_id[i], asynParamUndefined);
        }
        return;
    }

    struct fgc62_stat & stats = pub_data.status[dev_id].class_data.c62;

    // Bit mask symbol parsing
    std::string st_faults_str    = conv_fgc_flags(ntohs(stats.st_faults)      , sym_names_62_flt);
    std::string st_warnings_str  = conv_fgc_flags(ntohs(stats.st_warnings)    , sym_names_62_wrn);
    std::string st_latched_str   = conv_fgc_flags(ntohs(stats.st_latched)     , sym_names_62_lat);
    std::string st_unlatched_str = conv_fgc_flags(ntohs(stats.st_unlatched)   , sym_names_62_unl);
    std::string st_adc_a_str     = conv_fgc_flags(stats.st_adc_a              , sym_names_62_adc_status);
    std::string st_adc_b_str     = conv_fgc_flags(stats.st_adc_b              , sym_names_62_adc_status);
    std::string st_adc_c_str     = conv_fgc_flags(stats.st_adc_c              , sym_names_62_adc_status);
    std::string st_adc_d_str     = conv_fgc_flags(stats.st_adc_d              , sym_names_62_adc_status);
    std::string st_dcct_a_str    = conv_fgc_flags(stats.st_dcct_a             , sym_names_62_dcct);

    // Enum symbol parsing
    std::string state_pll_str    = conv_fgc_enum(stats.state_pll , sym_names_62_pll);
    std::string state_op_str     = conv_fgc_enum(stats.state_op  , sym_names_62_op);
    std::string state_vs_str     = conv_fgc_enum(stats.state_vs  , sym_names_62_vs);
    std::string state_pc_str     = conv_fgc_enum(stats.state_pc  , sym_names_62_pc);

    // Remaining values parsing, casted int32_t or float
    int32_t i_earth_pcnt_int = stats.i_earth_pcnt;
    int32_t i_err_ma_int     = ntohs(stats.i_err_ma);
    float   i_ref_float      = ntohf(stats.i_ref);
    float   i_meas_float     = ntohf(stats.i_meas);
    float   v_meas_float     = ntohf(stats.v_meas);
    float   v_capa_float     = ntohf(stats.v_capa);

    drv->setStringParam( param_id[0] , st_faults_str);
    drv->setStringParam( param_id[1] , st_warnings_str);
    drv->setStringParam( param_id[2] , st_latched_str);
    drv->setStringParam( param_id[3] , st_unlatched_str);
    drv->setStringParam( param_id[4] , state_pll_str);
    drv->setStringParam( param_id[5] , state_op_str);
    drv->setStringParam( param_id[6] , state_vs_str);
    drv->setStringParam( param_id[7] , state_pc_str);
    drv->setStringParam( param_id[8] , st_adc_a_str);
    drv->setStringParam( param_id[9] , st_adc_b_str);
    drv->setStringParam( param_id[10], st_adc_c_str);
    drv->setStringParam( param_id[11], st_adc_d_str);
    drv->setStringParam( param_id[12], st_dcct_a_str);
    drv->setIntegerParam(param_id[13], i_earth_pcnt_int);
    drv->setIntegerParam(param_id[14], i_err_ma_int);
    drv->setDoubleParam( param_id[15], i_ref_float);
    drv->setDoubleParam( param_id[16], i_meas_float);
    drv->setDoubleParam( param_id[17], v_meas_float);
    drv->setDoubleParam( param_id[18], v_capa_float);

    // Update parameter values
    // Note: In order to trigger the callbacks execution, an actual change in
    //       value or status has to happen.
    //       This forces the asynDriver flag 'modified' to be updated.
    //       Otherwise, the timestamp update is not guaranteed to occur...
    //       Hope this will be fixed in a future asynDriver release.

    // Validate params
    for(int i = 0; i < ASYN_PARAMS_62; i++)
    {
        drv->setParamStatus(param_id[i], asynParamUndefined); // Force callback
        drv->setParamStatus(param_id[i], asynSuccess);
    }

};



void Class62::invalidate_class_params(asynPortDriver * drv)
{
    ClassHandler::invalidate_class_params(drv);

    for(int i = 0; i < ASYN_PARAMS_62; i++)
    {
        drv->setParamStatus(param_id[i], asynTimeout);
    }
}



// End of file: ../../sw/kt/fgcepics/fgcudpSup/src/classes/class_62_params.cpp
