TOP=../..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += $(TOP)/fgccmdSup/protocols/fgccmd.proto

#=======================================
include $(TOP)/configure/RULES
