// ../../sw/inc/classes/62/62_stat.h - This file is automatically generated by `parser/Output/C/FGC_stat.pm`  DO NOT EDIT

#include <stdint.h>
#ifndef FGC62_STAT
#define FGC62_STAT

struct fgc62_stat
{
    uint16_t st_faults       ;  // Faults
    uint16_t st_warnings     ;  // Warnings
    uint16_t st_latched      ;  // Latched status
    uint16_t st_unlatched    ;  // Unlatched status
    uint8_t  state_pll       ;  // Phase-locked loop state
    uint8_t  state_op        ;  // Operational state
    uint8_t  state_vs        ;  // Voltage source state
    uint8_t  state_pc        ;  // Power converter state
    uint8_t  st_adc_a        ;  // ADC A status
    uint8_t  st_adc_b        ;  // ADC B status
    uint8_t  st_adc_c        ;  // ADC C status
    uint8_t  st_adc_d        ;  // ADC D status
    uint8_t  st_dcct_a       ;  // DCCT A status
    int8_t   i_earth_pcnt    ;  // Earth fault current (percent of trip level)
    int16_t  i_err_ma        ;  // Maximum error between current reference and measurement (mA)
    float    i_ref           ;  // Pulse reference
    float    i_meas          ;  // Current measurement (A)
    float    v_meas          ;  // Voltage measurement (V)
    float    v_capa          ;  // Capacitor voltage measurement (V)
    uint8_t  reserved0[4];
};
#endif
// End of file: ../../sw/inc/classes/62/62_stat.h
