// ../../sw/kt/fgcepics/fgcudpSup/src/classes/62/class_62_params.h - This file is automatically generated by `parser/Output/EPICS/asynDriver/FGC_handler.pm`  DO NOT EDIT

#ifndef CLASS_62_PARAMS_H
#define CLASS_62_PARAMS_H

#include <asynPortDriver.h>
#include "pub_data.h"
#include "class_base_params.h"

#define ASYN_PARAMS_62   32
#define ASYN_CLASS_ID_62 62



class Class62 : public ClassHandler
{
protected:
    const int class_id;
    int param_id[ASYN_PARAMS_62];

public:
    Class62(int id, int tag) : ClassHandler(id, tag), class_id(ASYN_CLASS_ID_62) {};
    virtual void create_class_params(asynPortDriver * drv);
    virtual void update_class_params(asynPortDriver * drv, Pub_data & pub_data);
    virtual void invalidate_class_params(asynPortDriver * drv);
};



#endif
// End of file: ../../sw/kt/fgcepics/fgcudpSup/src/classes/62/class_62_params.h
